config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :labels do
    member do
      get :show_picture
      get :download
    end
    collection do
      post :upload
    end
  end
end

app/models/label.rb
# == Schema Information
#
# Table name: labels
#
#  id                :integer          not null, primary key
#  data              :binary
#  original_filename :string
#  content_type      :string
#  created_at        :datetime
#  updated_at        :datetime
#

class Label < ActiveRecord::Base

  validates :data, presence: true
  has_many :stamps, dependent: :destroy

end

app/models/stamp.rb
# == Schema Information
#
# Table name: stamps
#
#  id         :integer          not null, primary key
#  label_id   :integer
#  image_id   :string
#  top        :float
#  left       :float
#  created_at :datetime
#  updated_at :datetime
#  width      :float
#  height     :float
#

class Stamp < ActiveRecord::Base

  belongs_to :label

  def to_hash
    {
        stamp_id: self.id,
        image_id: self.image_id,
        top: self.top,
        left: self.left,
        width: self.width,
        height: self.height,
        angle: self.angle
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to labels_path
  end
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  def index
    @labels = Label.order(:id)
  end

  def new
    @label = Label.new
  end

  def upload
    @label = Label.new

    if params[:label]
      data = params[:label][:data]
      if data
        @label.original_filename = data.original_filename
        @label.content_type = data.content_type
        @label.data = data.read
      end
    end

    unless @label.save
      return render action: :new
    end

    redirect_to action: :edit, id: @label.id
  end

  def edit
    @label = Label.find_by_id(params[:id])
  end

  def update
    @label = Label.find_by_id(params[:id])
    stamps = JSON.parse(params[:stamp_json])

    ActiveRecord::Base.transaction do
      @label.stamps = []
      stamps.each do |stamp|
        @label.stamps << Stamp.new(
            image_id: stamp['image_id'],
            top: stamp['top'],
            left: stamp['left'],
            width: stamp['width'],
            height: stamp['height'],
            angle: stamp['angle']
        )
      end
      @label.save!
    end

    redirect_to action: :index
  end

  def destroy
    @label = Label.find_by_id(params[:id])
    @label.destroy
    redirect_to action: :index
  end

  def show_picture
    label = Label.find_by_id(params[:id])
    send_data(label.data, type: label.content_type, filename: label.original_filename)
  end

  def download
    label = Label.find_by_id(params[:id])
    image = Magick::Image.from_blob(label.data).first
    image.format = 'PNG'

    label.stamps.each do |stamp|
      stamp_image = Magick::Image.read("app/assets/images/stamps/#{stamp.image_id}").first
      stamp_image.background_color = "none"
      stamp_image.rotate!(stamp.angle * 180 / Math::PI)
      stamp_image.resize!(stamp.width, stamp.height)
      image.composite!(stamp_image, stamp.top, stamp.left, Magick::OverCompositeOp)
    end

    send_data(image.to_blob, disposition: :attachment, type: 'image/png', filename: "file_#{label.id}.png")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_messages(*args)
    @error_count = 0
    @error_messages = []
    args.each do |arg|
      next if arg.nil?
      @error_count += arg.errors.count
      arg.errors.full_messages.each do |message|
        @error_messages << message
      end
    end
    render :partial => 'shared/error_messages'
  end
end

app/helpers/labels_helper.rb
module LabelsHelper
  def stamp_image_tag(stamp)
    style_value = "position:absolute; top:#{stamp.top}px; left:#{stamp.left}px;"
    content_tag :div, class: 'stamp_border', style: style_value, stamp_id: stamp.id do
      image_tag "stamps/#{stamp.image_id}", width: stamp.width, height: stamp.height, stamp_id: stamp.id
    end
  end
end

app/views/labels/edit.html.erb
<div class="row">
  <div class="col-md-6">
    <div id="canvas">
      <%= image_tag show_picture_label_path(@label), id: 'base_image' %>
      <% @label.stamps.each do |stamp| %>
        <%= stamp_image_tag(stamp) %>
      <% end %>
    </div>
  </div>
  <div class="col-md-6">
    <% (1..6).each do |ix| %>
      <%= image_tag "stamps/heart_#{ix}.png", width: 100, height: 100, image_id: "heart_#{ix}.png", class: 'stamp' %>
    <% end %>
  </div>
</div>

<%= form_for(@label) do |f| %>
  <%= hidden_field_tag :stamp_json, @label.stamps.map{|s| s.to_hash }.to_json %>
  <%= f.submit '保存', class: 'btn btn-primary' %>
<% end %>

app/views/labels/index.html.erb
<div class="container-fluid">
  <%= link_to '新しいラベルを作る', {action: :new}, class: 'btn btn-primary' %>

  <br><br>

  <table class="table">
    <tr>
      <th>ファイル名</th>
      <th></th>
    </tr>
    <% @labels.each do |label| %>
      <tr>
        <td><%= link_to label.original_filename, {action: :edit, id: label.id} %></td>
        <td class="text-right">
          <%= link_to '画像ダウンロード', {action: :download, id: label.id}, class: 'btn btn-default' %>
          <%= link_to '削除', {action: :destroy, id: label.id}, method: :delete, class: 'btn btn-danger', data: { confirm: '削除しますか？' } %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/labels/new.html.erb
<%= form_for(@label, url: {action: :upload}) do |f| %>
  <%= error_messages(@label) %>
  <div class="form-group">
    <%= f.label :data %>
    <%= f.file_field :data, class: 'form-control' %>
  </div>
  <%= f.submit '送信', class: 'btn btn-primary' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Geeoka</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'ワインラベルメーカー', labels_path, class: 'navbar-brand' %>
    </div>
  </div>
</nav>

<%= yield %>

</body>
<%= javascript_include_tag 'application' %>
</html>

app/views/shared/_error_messages.html.erb
<% if @error_count > 0 %>
  <div class="alert alert-danger" role="alert">
    <ul>
      <% @error_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>